### PR TITLE
Updated MDH subrepo to v2.12.0

### PR DESCRIPTION
**Pull request by toonetown**
Also updated the icon to match the new one in MDH 2.12

### CODE REVIEW

**Comment by toonetown** [comment]
You can download (to test) a built version of this extension (using _my_ Safari Developer ID) from [markdown-here.safariextz.zip](https://github.com/adam-p/markdown-here-safari/files/337548/markdown-here.safariextz.zip)

(Github won't let me upload a `.safariextz` file - even though it _is_ a `.zip` file - so it's also zipped.)

**Comment by ickc** [comment]
Hi, @toonetown, I was using your distribution of markdown-here, and today it said it became invalid. Do you know why?

**Comment by toonetown** [comment]
@ickc - Looks like my cert expired...I will get a new one built and uploaded. You may need to uninstall and reinstall. I will post back here when I have a new one. Sorry about that.

**Comment by ickc** [comment]
@toonetown, no problem! It's just that Apple is making this so difficult.

**Comment by toonetown** [comment]
OK - I've built another one and am hosting it at http://www.toonetown.com/nathan/projects/markdown-here/markdown-here.safariextz

You will likely need to uninstall and reinstall...since I decided to actually change the identifier that I was building as, and I had to generate a new Safari Developer certificate.  Sorry for any inconvenience.  It's actually good to know that someone is using what I'm building 😄

**Comment by ickc** [comment]
It isn't working on Safari 12 anymore, which classified this extension as "unsafe". Any plan to update this for the latest Safari? Many thanks.

**Comment by toonetown** [comment]
Nope - I no longer use it, and do not plan to update the build.  You might be able to build your own and load it as a developer extension.

**Pull request closed without merging**
